version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
      TEST: test